### ISSUE TITLE
Noticeable clipping/clicking in EA XAS samples

### ISSUE THREAD

**Issue by RAZORXKHARA33** [CrabJournal/ABK_Insert#6]
While the new encoder for Carbon+ ABKs properly scales the size of the ABK based on the size of samples used, it appears there's an issue with EA ADPCM. Namely, it adds very audible clipping/clicking to the samples. Attached is a file containing the samples before injecting into the ABK, as well as the samples decoded from the resulting ABK. While the uncompressed size between the two remains the same, it appears that there is actually some sort of data loss.
[CAR_64.zip](https://github.com/CrabJournal/ABK_Insert/files/8236437/CAR_64.zip)
@CrabJournal Is there anything that can be done to mitigate this? The source files are 16-bit signed WAV, 44.1KHz. I wonder if it has something to do with chunk size or something along those lines. If that's the case, there should be a way around it, right?

**Comment by RAZORXKHARA33** [comment]
Examining 2 files that are supposed to be roughly the same, the file decoded from the ABK has noticeably damaged waveforms in some areas, which is likely the cause of the clipping and artifacting.

**Comment by RAZORXKHARA33** [comment]
@CrabJournal Just had a look at the page for EA_ADPCM_codec (another one of your projects) and under TODO, it says "Reduce losses". I'm guessing those losses are what I'm hearing in the resulting ABKs, no? Regardless, my apologies for springing all of these issues onto you.

**Comment by CrabJournal** [comment]
I found the bug in encoder which is cause this clicking. The funny thing is that it was in piece of code which was written for reducing losses.

**Comment by RAZORXKHARA33** [comment]
> I found the bug in encoder which is cause this clicking. The funny thing is that it was in piece of code which was written for reducing losses.

That's good to hear. I'm looking forward to the next update. I may have jumped the gun in releasing my Carbon sound mod as I didn't notice that the clipping was caused by losses caused by the encoder. Anyway, thank you for the update.

**Comment by RAZORXKHARA33** [comment]
Latest release has fixed this issue for the most part (enough that I believe it can be closed).
