### ISSUE TITLE
Large file size difference exception

### ISSUE THREAD

**Issue by RAZORXKHARA33** [CrabJournal/ABK_Insert#7]
I'm not sure how to work around this exception getting thrown. I've tried shortening my samples to be the same length as the original samples in the target bank, but no matter what, I still get the "Large files size difference" exception thrown whenever I try to replace anything but one sample. That is to say, I can always modify 1 sample in an unmodified bank, but whenever I try to do more than 1 different sample, that exception gets thrown.

For example, when attempting to replace samples 1 and 5 in TURBO_SC_MBZ_MB.abk with the first and third samples from twinscrew_19.abk (downsampled to 22050 Hz to match MW05), I can replace sample 1 in the unmodified bank. I can also replace sample 5 in the unmodified bank. However, when I try to replace sample 1 AND sample 5, I get the large files size difference exception. This happens regardless of whether or not I shorten my new samples to match the length of the original samples. I have also tried replacing each sample in order (so inserting the unmodified samples 2-4 as well), but I still get that exception thrown upon trying to replace more than 1 sample. That is to say, it fails on sample 2, even though it's the same sample as in the unmodified bank.

**Comment by trackmaniamatt** [comment]
I've been experiencing the same issue as well, but when trying to encode an engine abk from Most Wanted. Specifically, CAR_12_ENG_MB_EE.abk. After importing samples 1, 2, and 3, the tool throws an error:
![ABK_Insert_error](https://user-images.githubusercontent.com/19352814/174701625-0648858b-9a7f-4018-a05f-a11f85ded9ff.jpg)

I've tried using different .wav files, but that didn't seem to fix it.

What would cause this error, and is there a workaround or fix to it?

**Comment by CrabJournal** [comment]
I made a critical bug in v3.1. Now it fixed in 3.1.1.
