### ISSUE TITLE
NFS Carbon: Tool breaks entirely after trying to import sounds

### ISSUE THREAD

**Issue by trackmaniamatt** [CrabJournal/ABK_Insert#8]
Hello, I have an issue to report with the latest version of the tool (v3.1).

Whenever I import a sound to a Carbon .abk file, It shows as if it imported the sound, but then it throws an error message.
Below is an attached image of the error message that was thrown.

What coud be causing this?
![Latest ABK Insert - Breaks When Importing New Sounds Entirely (NFS Carbon)](https://user-images.githubusercontent.com/19352814/161770610-9285a2eb-1487-4402-bcd7-b41cb179e266.png)

**Comment by trackmaniamatt** [comment]
I fixed it! Turns out I was using the wrong version of the EA_ADPCM_Codec.dll file (was using the x64 version, when I should have been using the x86 version). You can disregard this issue, and close it. :)

**Comment by RAZORXKHARA33** [comment]
@trackmaniamatt you should be able to close it as well, as the one who opened it.
@CrabJournal The x86 version should be shipped with the ABK_insert tool, rather than the x64 version that's currently included.

**Comment by CrabJournal** [comment]
I've updated 3.1 release, use new EA_ADPCM_codec.dll.
